server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    #是否需要获取服务信息
    fetch-registry: true
    #是否需要将自己注册到注册中心(注册中心集群需要设置为true)
    register-with-eureka: true
    #配置eureka服务器地址
    #https://blog.csdn.net/u011531425/article/details/81713441
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/